[build]
builder = "nixpacks"

[deploy]
startCommand = "node ./dist/server/entry.mjs"
restartPolicyType = "always"
restartPolicyMaxRetries = 5

[env]
HOST = "0.0.0.0"
NODE_ENV = "production"
FORCE_HTTPS = "true"
